export const ORDERMATRIX_FACTS = [
  'WhatsApp has over 500 million monthly active users in India alone.',
  'D2C brands that respond to inquiries within 5 minutes see 9× higher conversion rates.',
  'Order tracking messages have an 85% open rate — the highest of any business message type.',
  'The average cart abandonment rate in Indian e-commerce is 70%.',
  'WhatsApp Commerce can reduce customer acquisition cost by up to 40% versus traditional ads.',
  'Brands using automated order confirmations see a 30% drop in customer support tickets.',
  'Repeat customers spend 67% more on average than first-time buyers.',
  'Over 60% of D2C orders in India are placed from mobile devices.',
  'Personalised order status updates reduce "Where is my order?" calls by up to 60%.',
  'Flash sale campaigns sent via WhatsApp see 3× higher click-through than email.',
  'COD orders account for nearly 50% of e-commerce volume in India.',
  'A 5% increase in customer retention can boost profits by 25–95%.',
  'WhatsApp Business accounts with quick replies resolve queries 40% faster.',
  'Tier-2 and Tier-3 cities now drive over 55% of new D2C customers in India.',
  'Businesses that follow up on abandoned carts within 1 hour recover 10× more revenue.',
  'Chatbot-assisted order placement reduces human agent load by up to 70%.',
  'The average WhatsApp broadcast open rate is 98%, compared to 20% for email.',
  'Offering multiple payment options at checkout can increase conversions by 15%.',
  'Post-purchase surveys sent via WhatsApp get 5× more responses than email surveys.',
  'Subscription-based D2C brands have 3× higher lifetime value than one-time buyers.',
  'India\'s e-commerce market is projected to reach $350 billion by 2030.',
  'Brands with real-time inventory sync reduce stockout complaints by 45%.',
  'NPS scores improve by an average of 20 points when order tracking is automated.',
  'Over 75% of shoppers say they would buy again from a brand that resolves issues quickly.',
  'Same-day delivery can increase order value by up to 30% among urban shoppers.',
  'Visual product catalogues on WhatsApp drive 2× higher add-to-cart rates.',
  'Customer lifetime value is the single most predictive metric for D2C brand health.',
  'Proactive shipping alerts cut inbound delivery support queries by up to 50%.',
  'Referral programmes in WhatsApp-led commerce convert at 3× the rate of paid ads.',
  'More than 80% of Indian smartphone users have WhatsApp installed.',
  'Businesses replying to all reviews grow revenue 1.4× faster than those that don\'t.',
  'The average Indian D2C brand processes its peak daily order volume during 8–10 PM.',
  'Automated return and refund flows reduce resolution time from days to under 2 hours.',
];
